### ISSUE TITLE
what

### ISSUE THREAD

**Issue by pastel-n0va** [opera-gaming/gxmods#116]
this doesnt make any sense i just wanna make a opera gx mod and i dont know how to ****ing use GitHub please help

**Comment by triniterrax** [comment]
i help

**Comment by triniterrax** [comment]
past1
What type of mod are you going to create?

(Background music - dynamic music that fits browsing
Keyboard sounds - mechanical keyboard, typewriter, or sci-fi terminal sounds
Browser sounds - opening and closing tabs, clicking, flipping switches, etc.
Wallpaper - light and dark versions (static and animated)
Theme - color theme for light and dark mode
Web modding - tuning web pages to create unique appearances
Shaders - applying visual effects to the whole screen while browsing)

past 2
dowland visual studio code to the code

So that I can provide the corresponding next steps, please respond :)

**Comment by pastel-n0va** [comment]
theme and wallpaper

**Comment by triniterrax** [comment]
ok

**Comment by triniterrax** [comment]
to the theme create in visual studio a file ej
![image](https://github.com/opera-gaming/gxmods/assets/132803535/b92f7bf7-4856-4498-9616-634675add894)
![image](https://github.com/opera-gaming/gxmods/assets/132803535/d1f6cf00-de03-4cf3-bb8b-51ecdfc2d039)
![image](https://github.com/opera-gaming/gxmods/assets/132803535/a77d7969-9db2-4df6-8961-466e81404fa7)

**Comment by triniterrax** [comment]
{
    "manifest_version": 3,
    "name": "",
    "description": "MELODY.",
    "version": "1.0",
    "icons":
    {
        "512": "icon_512.png"
    },
    "developer":
    {
        "name": "Opera Software"
    },
    "mod":
    {
        "schema_version": 1,
        "payload":
        {
            "background_music":
            [
                "music/layer-001.mp3",
                "music/layer-002.mp3"
            ]
        }
    }
,
"wallpaper":
{
    "dark":
    {
        "image": "wallpaper/dark.jpg",
        "text_color": "#ffffff",
        "text_shadow": "#cccccc"
    },
    "light":
    {
        "image": "wallpaper/light.jpg",
        "text_color": "#ffffff",
        "text_shadow": "#cccccc"
    }
  }
}

**Comment by triniterrax** [comment]
for the theme create a  folder and put the music, the name of the music is layer-001.mp3 and layer-002.mp3 If you only have one music file, remove "music/layer-002.mp3" and remove the come for the "music/layer-001.mp3"(,)

**Comment by triniterrax** [comment]
and create a image to 512x512 ej
![image](https://github.com/opera-gaming/gxmods/assets/132803535/48a3fc07-c018-4791-9c5a-1af791a77f0e)

**Comment by triniterrax** [comment]
![image](https://github.com/opera-gaming/gxmods/assets/132803535/5805fcd6-a1d9-4585-8d62-b722f6ae8ed7)

**Comment by triniterrax** [comment]
So that I can provide the corresponding next steps, please respond :)

**Comment by pastel-n0va** [comment]
this doesnt make any sense i dont code

**Comment by TheLastWordussy** [comment]
i reccomend watching a youtube tutorial on how to do it 
i watched this one here: https://youtu.be/lSXGIlELV3s
i hope it helps

**Comment by crazycraft19** [comment]
Yeah I agree, go watch a YouTube video on it

Sent from my iPhone

On May 27, 2023, at 1:47 PM, The Last Word ***@***.***> wrote:

﻿

i reccomend watching a youtube tutorial on how to do it
i watched this one here: https://youtu.be/lSXGIlELV3s
i hope it helps

**Comment by pastel-n0va** [comment]
nvmd i'll just provide a link for the source of backgrounds, and close this issue
[pokemon-themed wallpaper](https://pokewalls.wordpress.com/tag/legendary/page/2/)
