### ISSUE TITLE
 Trying to do a mod but everytime i try to add/ change the bgmusic, this pops up: background_music: File doesn't exists:

### ISSUE THREAD

**Issue by RapidJamer** [opera-gaming/gxmods#117]
Trying to do a mod but every time i try to add/ change the bg music, this pops up: 

background_music: File doesn't exists:

It also goes for every song. If I delete said mp3, it says it too for another mp3, and so on so I need some help fixing it so I can get my first mod over with
![image_2023-05-25_204408612](https://github.com/opera-gaming/gxmods/assets/110575892/97f938ff-6ddf-42e8-8a2e-cb0b83a62812)
 first mod over with

**Comment by triniterrax** [comment]
"It's not better if you do it for mods."

**Comment by RapidJamer** [comment]
this ones just a personal one I procrastinated on for a few months, so I'm just trying to knock it out

**Comment by RapidJamer** [comment]
Nvm, solved. i didn't know you had to also add it to the music folder
