### ISSUE TITLE
Name preventing me from uploading.

### ISSUE THREAD

**Issue by MineBros101** [opera-gaming/gxmods#120]
I have another error where it says "A mod with the same title already exists" even when I changed the title to something random, such as "igurugvuiegvhreocnughillsncdhguoywehvlighcnlerghcyivn.zip" Help is needed!
Edit: I even checked if "igurugvuiegvhreocnughillsncdhguoywehvlighcnlerghcyivn" was already a mod. Spoiler: Its not.

**Comment by NotIncorecc** [comment]
#85 You need to change the name in the json file

**Comment by MineBros101** [comment]
I can't open it.

**Comment by MineBros101** [comment]
Oh, I got it to work. I just used a Notebook++ and it works.
Thanks for the help!
