### ISSUE TITLE
Very minor spelling issue in README

### ISSUE THREAD

**Issue by Emby01** [opera-gaming/gxmods#121]
![image](https://github.com/opera-gaming/gxmods/assets/99022462/32d82eec-1065-4f24-88aa-689801055ae7)
It should be "guidelines". Sorry if I'm being annoying

**Comment by anand346** [comment]
please assign this issue to me , I would love to fix it

**Comment by Emby01** [comment]
this was fixed a while back, forgot to close this issue
https://github.com/opera-gaming/gxmods/commit/c1bdfac131ef070efa956974a4f1c612adee7d31
