### ISSUE TITLE
My Music is not Working

### ISSUE THREAD

**Issue by DavoshiStudios** [opera-gaming/gxmods#136]
So I was finally done coding my mod. When I went to test it, my sounds were messed up. First of all, only the first soundtrack I coded in was looping, all the others never played. Second of all, when I opened a tab or clicked something on a website, one of those soundtracks (excluding the first one) would play. The sound would also play, but with the music behind it. I've looked all over the issues board, and to no avail, here I am. I have two pictures to help convey my problem.
![image](https://github.com/opera-gaming/gxmods/assets/138564940/58fbd707-a3df-4a93-94eb-06cc7d020fa5)
![image](https://github.com/opera-gaming/gxmods/assets/138564940/d932f165-ba22-4373-b1d9-77aa8133a758)

**Comment by DavoshiStudios** [comment]
Nvm I fixed it.

**Comment by miguel-lm** [comment]
Can you tell me how you did it? I have the same problem
