### ISSUE TITLE
Downloaded Mods Page Not Working

### ISSUE THREAD

**Issue by EliteNinja2084** [opera-gaming/gxmods#138]
My downloaded mods ( page opera://mods/# ) page blurs when I open it 
![image](https://github.com/opera-gaming/gxmods/assets/138089723/6df9b5b5-6b8b-43ab-981b-e3e1ab719d48)
Idk how to fix it.

**Comment by Mottoish** [comment]
Same Problem..

**Comment by EliteNinja2084** [comment]
> You Just Gotta Click This Button ![image](https://user-images.githubusercontent.com/138707530/251225553-4e222d8d-c1be-4078-a417-9d868fad7df3.png)

Thank you so much
