### ISSUE TITLE
Make the volume of the background music changeable 

### ISSUE THREAD

**Issue by xDrion** [opera-gaming/gxmods#21]
![Screenshot 2023-02-17 160154](https://user-images.githubusercontent.com/125661348/219648819-b41f94d2-6d25-46f0-8876-4f6938328022.png)
can you make it so that you can lower the background music

**Comment by themaciekk** [comment]
You can change volume of background music in settings: 
![image](https://user-images.githubusercontent.com/124875542/219653564-820aebd2-e3ac-4d9d-98b1-92ccf4983959.png)
