### ISSUE TITLE
MODs picture is not appearing

### ISSUE THREAD

**Issue by astoh3** [opera-gaming/gxmods#30]
so i tried doing my own mod, and i dont have any clue why it is not appearing.

![Screenshot (9)](https://user-images.githubusercontent.com/125594340/219955129-b2c07928-26e1-4320-8517-36bed65adb97.png)

![image_2023-02-19_171303455](https://user-images.githubusercontent.com/125594340/219953690-e8c76f8a-6268-429b-aafc-4beda34f79a7.png)

**Comment by astoh3** [comment]
nvrm it dose show after extensioning the pack

**Comment by TypicalHB** [comment]
This seems like a bug. Nothing seems to be incorrect. But this post should hopefully alert the developers and it'll be fixed soon 👍

(But on the off chance it's not a bug, maybe try using some different images and see if it works. It could have something to do with that specific image for whatever reason)
