### ISSUE TITLE
Mods Not installing

### ISSUE THREAD

**Issue by pseudo-Random-89** [opera-gaming/gxmods#7]
When I click install, the button changes to a loading icon before switching back to the regular install button.

**Comment by Drazzull** [comment]
Had the same issue, the button changes it background to red.
![image](https://user-images.githubusercontent.com/7754637/218904423-501fc7c2-e0a7-47f2-95a0-a07f5b1c7ee4.png)

Also shows a console error:
![image](https://user-images.githubusercontent.com/7754637/218904251-23c4a549-5aa3-4891-b7f4-b7c3b21ed6de.png)

**Comment by giraffe02** [comment]
I am currently having the same problem as well as the same error.

**Comment by Empresaurio17** [comment]
is there a solution?

**Comment by pugpower906** [comment]
I have the same issue ive been trying to fix it for over an hour and a half and i got nothing

**Comment by Lmorthian** [comment]
I just restarted my PC and it worked, idk what's going on for you guys.

**Comment by Drazzull** [comment]
> I just restarted my PC and it worked, idk what's going on for you guys.

Today it worked, probably the server was overloaded with too many requests.
You can see at my screenshot that the issue was going on the server:

> Had the same issue, the button changes it background to red. ![image](https://user-images.githubusercontent.com/7754637/218904423-501fc7c2-e0a7-47f2-95a0-a07f5b1c7ee4.png)
> 
> Also shows a console error: ![image](https://user-images.githubusercontent.com/7754637/218904251-23c4a549-5aa3-4891-b7f4-b7c3b21ed6de.png)

**Comment by astoh3** [comment]
> 

i still have the issue how ever, it worked after turning my VPN on

**Comment by astoh3** [comment]
> > I just restarted my PC and it worked, idk what's going on for you guys.
> 
> Today it worked, probably the server was overloaded with too many requests. You can see at my screenshot that the issue was going on the server:
> 
> > Had the same issue, the button changes it background to red.
> > ![image](https://user-images.githubusercontent.com/7754637/218904423-501fc7c2-e0a7-47f2-95a0-a07f5b1c7ee4.png)
> > Also shows a console error:
> > ![image](https://user-images.githubusercontent.com/7754637/218904251-23c4a549-5aa3-4891-b7f4-b7c3b21ed6de.png)



> > I just restarted my PC and it worked, idk what's going on for you guys.
> 
> Today it worked, probably the server was overloaded with too many requests. You can see at my screenshot that the issue was going on the server:
> 
> > Had the same issue, the button changes it background to red.
> > ![image](https://user-images.githubusercontent.com/7754637/218904423-501fc7c2-e0a7-47f2-95a0-a07f5b1c7ee4.png)
> > Also shows a console error:
> > ![image](https://user-images.githubusercontent.com/7754637/218904251-23c4a549-5aa3-4891-b7f4-b7c3b21ed6de.png)

I still have the issue however, it worked after turning on my VPN

**Comment by astoh3** [comment]
try using VPN if it didn't work, it did work for me

**Comment by pseudo-Random-89** [comment]
Nvm, works just fine now after a restart.
