### ISSUE TITLE
Mods not installing after update

### ISSUE THREAD

**Issue by deezus07** [opera-gaming/gxmods#71]
I installed the mod "Hero of Hyrule", but when I restarted Opera, the wallpaper is completely black, and 
![image](https://user-images.githubusercontent.com/129903982/229925015-b9c0ea80-aa63-4900-bc4d-6636184fcfa9.png)
the mod isn't allowing me to download it again, and it isn't in my installed menu. It says mod is already installed, but disabled. But, when I check my installed mods, it is not allowing me to even see it.
![image](https://user-images.githubusercontent.com/129903982/229926153-924ae3d7-4bc1-462e-89e6-582c2a59b672.png)
![image](https://user-images.githubusercontent.com/129903982/229926246-ddcba122-452e-4b27-afae-a158b2f9fc53.png)

**Comment by Fade2538** [comment]
try reinstalling it

**Comment by themaciekk** [comment]
What you describe could happen if the mod is disabled in extensions view (developer mode needs to be activated). 
Try those instructions. 


![enablemod](https://user-images.githubusercontent.com/124875542/230106670-9f310769-1188-43f6-b963-37c1e8756a76.png)

**Comment by deezus07** [comment]
thanks that worked
