### ISSUE TITLE
multiple songs in the background music plays as its browser sound 

### ISSUE THREAD

**Issue by TheLastWordussy** [opera-gaming/gxmods#78]
when i have more than 1 song coded into the background music it for some reason a song from that list plays like its a browser sound( click, open tab, close tab) and when remove all but 1 song from the list it stops doing that

**Comment by themaciekk** [comment]
Music is treated in another way. Those tracks are used for [vertical remixing](https://github.com/opera-gaming/gxmods/blob/main/documentation/mods.md#background-music). This means music will become more intense when user is actively using browser. You can check out how [Mod_Template](https://github.com/opera-gaming/gxmods/tree/main/documentation/Mod_Template) is using that feature.

If you want to have a "playlist" of multiple songs that are played one after another, you need to create one long music file with all those songs included.
