### ISSUE TITLE
Shader intensity adjustment [Feature Request]

### ISSUE THREAD

**Issue by Evryon75** [opera-gaming/gxmods#9]
It would be better if we could adjust the intensity of some shaders, the `Full Weather Cycle` is great, but it is also very distracting, just like most shaders.
<img width="400px" src="https://user-images.githubusercontent.com/79467907/218980342-7fcf7bb1-d565-4b8b-82ee-a1d25e2a34d8.png" />

**Comment by themaciekk** [comment]
You can include more than one shader in each mod and let users choose which version they want - distracting one for fun or a softer version to keep it on all the time. Have a look at the CTR shader.
